name: CI Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - name: Clone repo
        uses: actions/checkout@v3

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt "numpy<2" numexpr ruff

      - name: Lint code (ruff)
        run: ruff src scripts

      - name: Check scripts exist
        run: |
          test -f src/harvest_pubmed.py
          test -f run_pipeline.sh
